### ISSUE TITLE
Support for LocalDate type

### ISSUE THREAD

**Issue by Tom-Marvolo** [gasparbarancelli/spring-native-query#32]
**Is your feature request related to a problem? Please describe.**
I was trying to map a query result to java 8 LocalDate type field but got an exception: 
`IllegalArgumentException occurred while calling setter for property (expected type = java.time.LocalDate)];
`

**Describe the solution you'd like**
if we update the version of spring JPA to 2.2 or higher the exception should be resolved:
https://thorben-janssen.com/hibernate-5-date-and-time/

**Comment by gasparbarancelli** [comment]
To convert the result of native queries to java objects we use Hibernate's setResultTransformer method, but it is deprecated, it does not convert to new date objects. Because of this, the framework provides the queri execution with JdbcTemplate and it uses the BeanPropertyRowMapper and it does convert to the new date objects. To run the query as JdbcTemplate add the following annotation above your method in the NativeQuery interface. @NativeQueryUseJdbcTemplate

**Comment by gasparbarancelli** [comment]
I updated the spring boot dependencies as a result all hibernate and jpa dependencies have been updated.
