### ISSUE TITLE
Why use .twig instead of .sql?

### ISSUE THREAD

**Issue by sutra** [gasparbarancelli/spring-native-query#7]

**Comment by sutra** [comment]
OK, I got it.

We can use twig syntax like this as mentioned in README:
```
SELECT cod as "id", full_name as "name" FROM USER
WHERE 1=1
/* if (filterId != null) */
AND cod = :filterId
/* endif  */
/* if (filterName != null) */
AND full_name like :filterName
/* endif  */
```

**Comment by gasparbarancelli** [comment]
We can create a parameter so that the user can define the file extension. I believe that .sql would be ideal, but we can't change that now as it will break many existing projects. But for now we will add a new property in application.properties with the name "native-query.file.prefix" where the default value will be twig but leaving the possibility for the user to change.

**Comment by gasparbarancelli** [comment]
We can create a parameter so that the user can define the file extension. I believe that .sql would be ideal, but we can't change that now as it will break many existing projects. But for now we will add a new property in application.properties with the name "native-query.file.sufix" where the default value will be twig but leaving the possibility for the user to change.
